# Size of RaptorQ block, in bytes
encoding_block_size = 60000

# Size of repair data, in bytes
repair_block_size = 6000

# IP address on diode-receive side used to transfert UDP packets between diode-send and diode-receive
udp_addr = "127.0.0.1"

# List of ports used to transfert packets between diode-send and diode-receive. There must be one different port per thread.
udp_port = [ 5000 ]

# MTU of the to use one the UDP link
udp_mtu = 1500

# heartbeat period in ms
heartbeat = 1000

# Path to log configuration file
# log_config = "./lidi_log4rs.yml"

# specific options for diode-send
[sender]
# TCP server socket to accept data
bind_tcp = "127.0.0.1:5001"

# IP address and port of the TCP server
bind_udp = "127.0.0.1:0"

# ratelimit TCP session speed (in bit/s).
max_bandwidth = 10000000

# prometheus port
metrics = "0.0.0.0:9001"

# specific options for diode-receive
[receiver]

# IP address and port of the TCP server
to_tcp = "127.0.0.1:5002"

# Timeout before forcing incomplete block recovery (in ms). Default is one time heartbeat interval.
# block_expiration_timeout = 500

# Session expiration delay. Time to wait before changing session (in ms). Default is 5 times heartbeat interval.
# session_expiration_timeout = 5000

# prometheus port
metrics = "0.0.0.0:9002"

# core_affinity = [ 1 ]
